# Generated by Django 4.2.1 on 2023-06-05 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favorites',
        ),
        migrations.RemoveConstraint(
            model_name='favorites',
            name='api_favorite_unique',
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='api_favorites_unique'),
        ),
    ]
