version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    ports:
  
      - "5432:5432"
    env_file:
      - ./.env

  backend:
    image: i9800995516/foodgram_backend:latest
    command: >
      sh -c "python manage.py collectstatic --no-input &&
               python manage.py migrate &&
               python manage.py import_date
               gunicorn foodgram.wsgi:application --bind 0:8000"
    
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: i9800995516/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes: 
  static_value:
  media_value:
  db_value:
