# Generated by Django 3.2 on 2023-06-25 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipekorzina',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='shopping', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipekorzina',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='shopping', to=settings.AUTH_USER_MODEL),
        ),
    ]
