# Generated by Django 3.2 on 2023-07-02 23:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20230629_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeKorzina',
            new_name='Cart',
        ),
    ]
