# Generated by Django 3.2 on 2023-07-03 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_recipekorzina_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientsmerge',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество не может бытьменьше {MIN_INGREDIENT_VALUE}')], verbose_name='Количество'),
        ),
    ]
