# Generated by Django 3.2 on 2023-07-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredientsmerge_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_korzina_user_recipe',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_cart_user_recipe'),
        ),
    ]
