# Generated by Django 3.2 on 2023-07-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_follow_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recipes_limit',
            field=models.IntegerField(default=3),
        ),
    ]
