# Generated by Django 3.2 on 2023-07-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_recipes_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recipes_limit',
        ),
    ]
